2023-12-25 22:27:28,442 DEBUG    root            Loaded Command Group: ['gcloud', 'auth']
2023-12-25 22:27:28,443 DEBUG    root            Loaded Command Group: ['gcloud', 'auth', 'application_default']
2023-12-25 22:27:28,446 DEBUG    root            Loaded Command Group: ['gcloud', 'auth', 'application-default', 'print_access_token']
2023-12-25 22:27:28,448 DEBUG    root            Running [gcloud.auth.application-default.print-access-token] with arguments: [--quiet: "True", --verbosity: "warning"]
2023-12-25 22:27:28,448 DEBUG    google.auth.transport._http_client Making request: GET http://169.254.169.254
2023-12-25 22:27:31,450 WARNING  google.auth.compute_engine._metadata Compute Engine Metadata server unavailable on attempt 1 of 3. Reason: timed out
2023-12-25 22:27:31,450 DEBUG    google.auth.transport._http_client Making request: GET http://169.254.169.254
2023-12-25 22:27:34,452 WARNING  google.auth.compute_engine._metadata Compute Engine Metadata server unavailable on attempt 2 of 3. Reason: timed out
2023-12-25 22:27:34,454 DEBUG    google.auth.transport._http_client Making request: GET http://169.254.169.254
2023-12-25 22:27:34,455 WARNING  google.auth.compute_engine._metadata Compute Engine Metadata server unavailable on attempt 3 of 3. Reason: [Errno 64] Host is down
2023-12-25 22:27:34,455 DEBUG    root            Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
Traceback (most recent call last):
  File "/Users/prathyureddy/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/surface/auth/application_default/print_access_token.py", line 117, in Run
    creds, _ = c_creds.GetGoogleAuthDefault().default(
  File "/Users/prathyureddy/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/third_party/google/auth/_default.py", line 648, in default
    raise exceptions.DefaultCredentialsError(_CLOUD_SDK_MISSING_CREDENTIALS)
google.auth.exceptions.DefaultCredentialsError: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
2023-12-25 22:27:34,459 DEBUG    root            (gcloud.auth.application-default.print-access-token) Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
Traceback (most recent call last):
  File "/Users/prathyureddy/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/surface/auth/application_default/print_access_token.py", line 117, in Run
    creds, _ = c_creds.GetGoogleAuthDefault().default(
  File "/Users/prathyureddy/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/third_party/google/auth/_default.py", line 648, in default
    raise exceptions.DefaultCredentialsError(_CLOUD_SDK_MISSING_CREDENTIALS)
google.auth.exceptions.DefaultCredentialsError: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/prathyureddy/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/Users/prathyureddy/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 807, in Run
    resources = command_instance.Run(args)
  File "/Users/prathyureddy/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/surface/auth/application_default/print_access_token.py", line 121, in Run
    raise c_exc.ToolException(six.text_type(e))
googlecloudsdk.calliope.exceptions.ToolException: Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
2023-12-25 22:27:34,462 ERROR    root            (gcloud.auth.application-default.print-access-token) Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
